idf_component_register(
                        SRC_DIRS 
                            "."
                            "APP/MIPI_CAM" 
                            "APP/PLANT_DISPLAY"
                            "APP/PLANT_ENGINE"
                            "APP/PLANT_SENSOR"
                            "APP/PLANT_TOUCH"
                        INCLUDE_DIRS 
                            "."
                            "APP/MIPI_CAM" 
                            "APP/PLANT_DISPLAY"
                            "APP/PLANT_ENGINE"
                            "APP/PLANT_SENSOR"
                            "APP/PLANT_TOUCH"
                        )
